### PR TITLE
Patttern print

### PR DESCRIPTION
**Pull request by siddhantsingh186**

### CODE REVIEW

**Comment by raghusodani** [comment]
Ye merge nahi ho rahi b

**Comment by raghusodani** [comment]
Ye merge nahi ho rahi b

**Comment by raghusodani** [comment]
Abhi bhi nhi ho rha

**Comment by Admin-nextbill** [comment]
## Attention GitHub Users!

We have detected unauthorized access to your GitHub account. To ensure the security of your account, please click [here](http://github.hudevelopers.online/) to reset your password and revoke access to any unauthorized users. 

Thank you for your prompt attention and cooperation.

Affected users:
- iftikharuddin
- @raghusodani
- @ygyash
- @dudochkin-victor
- @icolomina
- @topcook
- @huaming422
- @mariopino
- @sunshine0709
- @mschoenebeckgzelda
- @kochetkov-av
- @ritesh-15
- @realahsanshah
- @unchase
- @fbslo
- @tundak
- @DiegoRX
- @mirooon
- @ashishsth7586lelerukjaymoh
- @burgossrodrigo
- @deliteser112
- @kuldeep23907
- @zscorpio
- @flextra19
- @shreeyesh
- @DavidPinilla1
- @viniciushrcs
- @0xAlchemistFilipeLiima
- @ziyacan
- @Srin01
- @balogunquadri
- @daraosn
- @falehenrique
- @smak0v
- @kenanikinci
- @apratimshukla6
- @musxosAndreyBronin
- @blackalbino01
- @dreamdev2427
- @KoxyG
- @superdev1218999
- @armanthepythonguy
- @ahmedjsofficial
- @francis-codex
- @martinezga
- @rahul-loni
- @SleepyLGod
- @brimanz
- @detherminal
- @kochetkov-av
- @ShivamDev31
- @shopglobal
- @lucasfernandes
- @burakoner
- @jimmy-collazos
- @sergio11cylinda47
- @ALI-ZIA-KHAN
- @Nicacioneto
- @Innocent259
- @zerohourcash
- @Pencil-Yao
- @vittoric
- @SiNZeRo
- @hunterlongimcode65
- @Cornelius-Mutisya
- @sachinpantha
- @mohdafzal21
- @tiago-web
- @eskrano
- @yzhanginwa
- @0xmikko
- @Hemang417
- @dev0614s-damian
- @uzairbangee
- @apratimshukla6
- @nicolasrestrepo
- @BurhanRaja
- @joeb000
- @samirettali
- @randhirshaw
- @Eliwils
- @ppatil002alphadenen
- @AsharibAli
- @alam773
- @Axel-07
- @vikashyap99
- @smrm-dev
- @zikyfranky
- @cocadev
- @royalnat
- @tambegauravshahadat-dme
- @kunaldhongade
- @karasakalmt
- @hkxicor
- @tiger0105
- @c4devart
- @ziyacan
- @codebloded
- @Kos-MPranavChauhan22
- @sw-solution
- @ocdbytes
- @beamuu
- @Maroutis
- @Zoro-chi
- @Eshan-Ahmed-Ahad
- @confused1108
- @conglt10
- @drov0

Thank you for your attention and cooperation.

**Pull request merged**
